### ISSUE TITLE
applyConstraint with depthMapUnit should only be rejected if mandatory

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-depth#107]
May be moot because of #100 - but otherwise I think the promise should only be rejected based on this if depthMapUnit is mandatory.

**Comment by jan-ivar** [comment]
Assuming we do what's suggested in https://github.com/w3c/mediacapture-depth/issues/100 (rename to something like `depthPrecision` and standardize values on an API unit), then why couldn't users change `depthPrecision` with `applyConstraints`?  Constraints let tabs negotiate for a shared resource, and I see no reason UAs couldn't handle this.

Other issues:
- Typo: We can't have `unit` in both `MediaTrackConstraintSet` and `MediaTrackConstraints`, since the latter is derived from the former.
- Use DOMString instead of WebIDL enum in constraints (see [facingMode](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-MediaTrackSettings-facingMode)).
- To support mandatory constraints (e.g. `applyConstraints({ depthPrecision: { exact: "m" } })`, the type in `MediaTrackConstraintSet` needs to be `ConstrainDOMString` (again like facingMode).

**Comment by jan-ivar** [comment]
Also:
- Default values must be avoided in `MediaTrackConstraintSet`, as a rule. *

*) because default values get implicitly inserted by webidl binding code to provide implementations with invariants, which is great, except `MediaTrackConstraintSet` is reused in `advanced` where the semantics of absence differs from providing a (default) value.

**Comment by anssiko** [comment]
This issue fixed itself:
- `applyConstraints()` special casing was removed in 13132ae as agreed in #118.
- `depthMapUnit/DepthPrecisionEnum` was removed in 461fd20 as agreed in #100.
