### ISSUE TITLE
Accessing Camera Calibrations

### ISSUE THREAD

**Issue by bbernhar** [w3c/mediacapture-depth#110]
I see the importance that we should consider allowing the UA to access calibration data. It would enable many useful computer vision scenarios and bring the need to enable at-least three calibrations:
- Spatial coordinate system: This gives us ability to project and unproject 2D image space to 3D camera space and map between locations of depth and the corresponding color image. Ideally, this wouldn't be done on a per-pixel basis and a coordinate system could represent the UA's world position too.
- Lens distortion: The UA can remove distortion from the image as not all cameras use high-distortion lenses.
- Camera re-sectioning: This can unproject 2D point to 3D space as ray (3D surface reconstruction from image or "skeletal tracking").
  
  The `v1` spec does not mention how or which calibration is used unlike the more verbose SDK-specific APIs [1] [2] and it seems necessary to expose these intrinsic operations and properties that can be performed on streams that belong to the same group of 3D devices.

@anssiko @huningxin WDYT?

[1] https://msdn.microsoft.com/en-us/library/dn785530.aspx
[2] https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/doc_essential_coordinates_mapping.html

**Comment by anssiko** [comment]
@bbernhar Thanks for raising this issue. I believe this hinges on the question how to do the split between v1 and v2 features.

Could you craft a proposal (in plain text, as a comment to this issue) with the intrinsic operations and properties that form the intersection of the capabilities of the most popular devices that are widely shipping? I assume these would be exposed via `MediaTrackSettings`?

Also, explaining the use cases might be helpful too. Your three scenarios already shed some light, but it may not be clear to everyone what the concrete usage scenarios are we'd miss if we'd defer these to v2.

**Comment by bbernhar** [comment]
Thanks @anssiko. This seems beyond the `v1` horizon but here are the basic problems I can see that need further discussion. There exist equivalent operations that ship for Kinect and RealSense, at-least (links below).

### Spatial Coordination

Uses calibrations from streams to reason with the related coordinate systems.

UC: Skeletal or 3D tracking of objects [1].

Detect where some object identified in depth space is in color space:

```
var objectPointsInDepth = ... // array of 2D points in depth space

//  Acquire & update per frame.
var depthCoordSys = depthStream.coordSys()
var colorCoordSys = colorStream.coordSys()

var objectsPointsInColor = depthCoordSys.map(objectPointsInDepth, colorCoordSys)
```

Render object in 3D from color or "video" space into 3D with depth:

```
var point3D = depthCoordSys.Unproject(pointFromColor, colorCoordSys)
```

[1] https://msdn.microsoft.com/en-us/library/dn785530.aspx

### Lens distortion

UC: correcting and removing lens distortion [1].

```
// Alternatively, we could consider exposing the look-up table or intrinsics through MediaTrackSettings
// This is fairly low-level and might be better handled with coordSys()?
var undistortImage = depthStream.mapUndistort(image)
```

[1] https://software.intel.com/en-us/node/504545

### Resectioning

https://en.wikipedia.org/wiki/Camera_resectioning

UC: 3D scanning.

Unproject 2D point from depth space into camera space:

```
var cameraPoint3D = depthStream.Unproject(depthPointXY)
```

Project a 3D point in camera space onto depth space:

```
var depthPointXY = depthStream.Unproject(cameraPoint3D)
```

https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/index.html?pxcprojection.html

**Comment by huningxin** [comment]
@bbernhar , +1 for this important topic. I am happy you raise it. 

My thoughts:

In current spec, there is an "Implementation considerations" section for color-depth mapping (registration). http://w3c.github.io/mediacapture-depth/#implementation-considerations

"A video stream track and a depth stream track can be combined into one depth+video stream. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources."

In this way, web app is able to get the color-depth mapped images, so each pixel has (R, G, B, X, Y, Z) information. The color-depth mapping is done in native or even hardware/firmware effectively.

Previously, for image pixel to world (camera) point conversation (or vise versa),  the focal length, fov (vertical and horizontal) were introduced (http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary). This is not completed, as the distortion is not addressed. According to http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html, we may add radial distortion coefficients and tangential distortion coefficients to complete this. @robman for comments as well (this is a follow-up to our previous discussion https://github.com/w3c/mediacapture-depth/issues/27).

For two cameras coordinates conversion, another option is to expose the camera extrinsics (rotation matrix and translation vector).  Then it is up to web app to do the conversion. I found sample implementations for both Intel RealSense camera (https://github.com/IntelRealSense/librealsense/blob/cefe5f758407fd49374b40ed2bcb2a1192b38ff8/include/librealsense/rsutil.h#L53) and for MSFT Kinect (http://nicolas.burrus.name/index.php/Research/KinectCalibration).

**Comment by bbernhar** [comment]
> Previously, for image pixel to world (camera) point conversation (or vise versa), the focal length, fov (vertical and horizontal) were introduced (http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary). This is not completed, as the distortion is not addressed. According to http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html, we may add radial distortion coefficients and tangential distortion coefficients to complete this. @robman for comments as well (this is a follow-up to our previous discussion #27).

@huningxin If we expose those low-level intrinsics directly through `MediaTrackSettings`, wouldn't one be invited to develop and use models that are wrongly calibrated with other cameras? I wouldn't expect users to "hold up a checker board" to lookup those calibrations either. I see value in a API that doesn't require users or developers to deal with these gory details but still allows them to reason with the related coordinate systems.

**Comment by huningxin** [comment]
> I wouldn't expect users to "hold up a checker board" to lookup those calibrations either.

By exposing the camera intrinsics and extrinsics, it doesn't require users "hold up a checker board" to do calibration. The reason of doing that is find out the camera intrinsics and extrinsics. :)

But I agree there are many details in the algorithm and dependencies of device. E.g. Intel RealSense Camera F200/SR300 and R200 has different configurations (https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/index.html?streamcalibration_pxccalibration.html). And some cameras' SDK even don't expose them (Kinect?). So dealing with them with an API would be a good idea.

As the `CooridnateSystem` would be added into `video` track as well, do you know the support in today's web cam API? Or limit the usage on for 3D camera (color + depth in one module)?

**Comment by anssiko** [comment]
Good discussion. Can we identify a subset of features that would be must have in the v1 spec? @bbernhar seemed to imply the features discussed in this issue would be beyond v1. From the comments I can gather that the following use cases would be hard (or impossible?) to implement without the features discussed in this issue:
- skeletal or 3D tracking of objects
- correcting and removing lens distortion
- 3D scanning

If we look at e.g. the [initial list of use cases identified](https://www.w3.org/wiki/Media_Capture_Depth_Stream_Extension#Use_Cases), does that still leave us with a good set of common use cases that can be implemented using the API?

(In general, a good idea is to ship a v1 spec that enables the most common use cases, and defer more advanced use cases to v2. By shipping v1 we'll get valuable feedback from web developers, since quite often not all usages can be anticipated up front. Often web developers also implement their own convenience libraries on top that can inform the v2.)

**Comment by bbernhar** [comment]
> The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources.

If I understand correctly, this describes a "whole frame" color-to-depth mapping function. Is that correct? The result being similarly accomplished with the RSSDK `Projection` method, `CreateColorImageMappedToDepth` or Kinect SDK `CoordiateMapper` method `MapColorFrameToDepthSpace`.

```
// Request color+depth via gUM(...)
var rgb = colorImageData[colorSpaceX][colorSpaceY]
var z = depthImageData[colorSpaceX][colorSpaceY] // spatially aligned & calibrated
var rgbxyz = {rgb,colorSpaceX,colorSpaceY, z}
```

But if you post-process (e.g. filter) pixels from depth space, how does one map them back to the corresponding color pixel? Furthermore, why map the _whole_ frame if only certain points were needed? It seems it would be very hard for us to consider supporting future mapping operations with the `v1` design.

> As the CooridnateSystem would be added into video track as well, do you know the support in today's web cam API? Or limit the usage on for 3D camera (color + depth in one module)?

The 3D cameras APIs I've seen offer the equivalent video source for color. Unfortunately, they may not be available through the existing media pipeline that's used for the webcam.

I'm not completely certain which features depend on what mapping operations, that is a far larger question to which the community is needed to decide (perhaps based from `v1` feedback?). It is however, much clearer that exposing calibrations is non-orthogonal to this problem.

**Comment by huningxin** [comment]
> If I understand correctly, this describes a "whole frame" color-to-depth mapping function. Is that correct?

@bbernhar , correct!

> But if you post-process (e.g. filter) pixels from depth space, how does one map them back to the corresponding color pixel?

So your use case depends on the depth-to-color mapping, is it? It was not considered before, I guess whether we can introduce `coordinate` constraint for that, like `{vidoe: true, depth: {coordinate: video}}` or `{video: {coordinate: depth}, depth: true}`, to handle that. Web app might be able to set the `coordinate` at runtime to change the mapping.

> Furthermore, why map the whole frame if only certain points were needed?

If the use case doesn't need the whole texture, it doesn't make sense to map the whole frame. @bbernhar , do you have some use cases about the partial mapping? 

I agree doing the whole frame mapping is CPU intensive, but I am aware some devices is offloading the mapping to DSP or firmware on camera. But I am not sure whether it is a momentum.

> Unfortunately, they may not be available through the existing media pipeline that's used for the webcam.

Thanks for this information.

> It is however, much clearer that exposing calibrations is non-orthogonal to this problem.

Agree.

**Comment by bbernhar** [comment]
@anssiko I'm not certain that anything but UC1 can be accomplished with only whole frame color-to-depth mapping. We need to actually verify this as the design direction of the native SDKs suggest this is also very limited.

> "A video stream track and a depth stream track can be combined into one depth+video stream. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources."

The color and depth images have different resolutions, so it seems reasonable to expect that any algorithm might need the information of some depth value from a corresponding color pixel. 

> If the use case doesn't need the whole texture, it doesn't make sense to map the whole frame. @bbernhar , do you have some use cases about the partial mapping?

@huningxin Aside from also wasting both bandwidth and power, you cannot calculate sub-pixel precision mapping nor perform a specific hole-fill optimization that would be best or fastest per usage. Partial mapping is also used for pixels "out of range" but remain meaningful to the algorithms (i.e. boundary pixels).

**Comment by anssiko** [comment]
@bbernhar Do you foresee camera calibration features discussed in this issue #110 being forward compatible with v1 (let's call the current spec v1 for simplicity)?

IOW, can we ensure the browsers that implement v1 will gracefully accept content written for the v2 API that bakes in camera calibrations? Naturally, the lack of calibrations would mean the experience is of lower quality if v1 implementation consumes content that assumes v2, to the extend that some use cases may not be practical.

As usual, we can assume web developers will make use of defensive techniques such as feature detection to figure out which part of the API surface is implemented and branch their code accordingly.

If we can guarantee forward compatibility, then it would very much make sense for the group to move forward with v1 in terms of wider review outside TF and encourage work on implementations in parallel to v2 feature development.

**Comment by bbernhar** [comment]
I don't have an issue with moving forward with `v1` and revisiting this for `v2`+. However, I remain uncertain to say that anything but UC1 is do-able.

**Comment by ds-hwang** [comment]
I agree on @huningxin. keep `v1` minimal and then generalize it when needed. camera calibration is different among all devices. Implementation detail has to handle

> "A video stream track and a depth stream track can be combined into one depth+video stream. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources."

**Comment by anssiko** [comment]
I tagged this as a v2 issue. Let's ship an API that can handle UC1 MVP-style and add more features in subsequent updates.

**Comment by astojilj** [comment]
I think we should make this V1 and #138 V2.
This one is simpler to implement and is the lowest common denominator required to implement various use cases with no need to have the same code replicated in all of the browsers (the functionality would fit JS library and WebGL better).

In [comment to #138](https://github.com/w3c/mediacapture-depth/issues/138?_pjax=%23js-repo-pjax-container#issuecomment-259838174) I explained why this would bring better performance to e.g. pointcloud.

Implementation could be like this:
1) Intrinsic parameters have the same semantics (and even the signature in some cases) in [RealRense's `rs_intrinsics`](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.h#L264) and in e.g. [Tango](https://developers.google.com/tango/apis/c/reference/struct/tango-camera-intrinsics).
The distortion models are different.
Intrinsic parameters could fit to [MediaTrackCapabilities](https://www.w3.org/TR/mediacapture-streams/#idl-def-MediaTrackCapabilities).

2) Extrinsics - transformation from one camera to another. @huningxin, do you know if we can consider this constant for one camera model and avoid reading it from the device? Otherwise, we'll could also fit the dictionary to MediaTrackCapabilities as matrix transformation to reference point, e.g. capture device on index 0 or something similar.

Naming and semantics of the data is fairly standardized among different device vendors:
[Microsoft Kinect2](https://msdn.microsoft.com/en-us/library/microsoft.kinect.kinect.cameraintrinsics.aspx), [Android Tango](https://developers.google.com/tango/apis/c/reference/struct/tango-camera-intrinsics) and [Intel RealSense cameras](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.h#L264) cameras define:

Intrinsics:
double focalLengthX // used to calculate horizontal field of view
double focalLengthY // used to calculate vertical field of view
double principalPointX // coordinate on the image, in pixels.
double principalPointY // coordinate on the image, in pixels.
string distortionModel; // name of distortion model, several different in use but with similar logic.
double distortionParameters[5] // Kinect names 3 parameters.
width // already in MediaTrackSettings
height // already in MediaTrackSettings

Extrinsics:
Position of cameras to common reference position (vector with origin). Used for projecting from one camera space to another.
double[4] rotation, // quaternion defining rotation
double[3] translation // vector defining translation

MediaTrackSettings looks like it could fit these too, but we could also define additional MediaTrackCaptureIntrinsics and MediaTrackCapturePosition. We already handle focal length (see Issue #135 ), width and height in MediaTrackSettings so let's try to fit the other, too.

**Comment by huningxin** [comment]
> Extrinsics - transformation from one camera to another. @huningxin, do you know if we can consider this constant for one camera model and avoid reading it from the device?

I think they should be read from the device.

@fluffy and @robman , in https://github.com/w3c/mediacapture-depth/issues/134, you proposed the  camera extrinsics/direction/pose, could we consolidate the discussions with this issue?

**Comment by robman** [comment]
+1 to consolidating all the extrinsics/intrinsics discussions into this one issue 8)

I think for v1 we can go with only intrinsics and just start with the simplest possible - image width/height and focal length x/y as discussed in #135 (all in pixels).

From this we can derive aspect ratio, fov's, projection matrix and (with depth map near/far) frustum.

Then for v2 we could add in more non-common things like principal point and distortion.

I think v2 would be more logical for extrinsics too.

**Comment by astojilj** [comment]
> I think for v1 we can go with only intrinsics and just start with the simplest possible - image width/height and focal length x/y as discussed in #135 (all in pixels).

v1&v2 scope feature split boils down to a question Issue #145.

**Comment by huningxin** [comment]
> I think for v1 we can go with only intrinsics and just start with the simplest possible - image width/height and focal length x/y as discussed in #135 (all in pixels).

@robman , the intrinsics (no matter simple or full set) are for reprojection which is essential to `UC5: Mobile Augmented Reality and Spatial Scanning` in [wiki](https://www.w3.org/wiki/Media_Capture_Depth_Stream_Extension), am I correct?

If v1 doesn't expose principal point and distortion, do you suggest just ignore them or let UA handle that, saying undistorting in native? Any impacts to UC5?

**Comment by astojilj** [comment]
@robman, @huningxin 
I see that @huningxin's question is not difficult to answer.
De-projection and undistortion is not correct with only partly provided calibration - proposed would offer API that exposes errors. 

@robman, could we please move this forward? There is a PR implementing this but is blocked on your proposal about [v1 and v2 split](https://github.com/w3c/mediacapture-depth/issues/110#issuecomment-260587927). Thanks.

**Comment by astojilj** [comment]
Continuing argumentation why providing only part of intrinsics is not enough (that we need all the intrinsics and mapping depth to rgb camera space.):
For any eventual hand/gesture recognition in JS, to get lowest latency user would probably choose to use row depth data (unsynchronized to RGB as synchronizing depth to rgb for every point takes time) to detect where the e.g. hand is.
When detecting the position in depth space, user would re-project only the position of hand to rgb space when displaying it. For proper reprojecting all of the data is needed.,
@robman  seems to be away, @anssiko is away too, so we will probably need to wait here for everybody to return. Meanwhile, we could start prototyping access to partially defined intrinsics parameters in Chromium.
