### ISSUE TITLE
How to handle depth conversion when range has a near value of zero.

### ISSUE THREAD

**Issue by bbernhar** [w3c/mediacapture-depth#125]
The RSSDK `PROPERTY_DEPTH_SENSOR_RANGE` property [1] can return a value of zero for `MinDepth`. Using our _convert using range inverse_  (per 6.6), the depth map will only quanitize to `dn=1` when near=0 and will inaccurately compute the interpolated depth values when converted into the grayscale image.

This is because the depth range (i.e. `MinDepth` and `MaxDepth` properties) can be reported as "effective range" or "camera range". If the formula uses camera range (what the RSSDK uses), the conversion output is not usable depth.

Effective range (i.e. MinDepth >0) would require computation on the depth frame, since hard coding "ideal" values isn't a long-term solution. However, this would be rather expensive given one would need to re-compute the range every frame.

I don't have a good solution there; other than to avoid the conversion altogether (e.g. move away from 8-bit depth) or just hard code ideal "effective range" values so we could avoid always processing each pixel per frame. Alternatively, we could define the behavior to only compute the range once upfront and leave the computation to script. 

[1] https://software.intel.com/sites/landingpage/realsense/camera-sdk/v1.1/documentation/html/index.html?property_device_pxccapture.html

**Comment by anssiko** [comment]
We will need the 8-bit representation for backwards compatibility reasons, interop with `<video>` and friends. In the future we can get 16-bit depth in a worker with a new set of APIs in the making (see [mediacapture-worker](https://w3c.github.io/mediacapture-worker/)). That said, we should figure out a solution to this 8-bit issue.

I think we should specify that both the near and far values must be positive values, and note that they represent the effective range, and not the camera range (which apparently can be zero). From implementation point of view, that'd might mean hardcoding the values.

@bbernhar won't you need to do the same conversion regardless of using the effective or camera range? I mean this conversion pipeline: raw depth measurement in mm -> normalize to [0,1] range to get d<sub>n</sub> -> quantify to [0,255] range to get d<sub>8bit</sub> ... stays the same.

Or do some implementation actually provide d<sub>8bit</sub> natively?

@huningxin to comment.

**Comment by bbernhar** [comment]
@anssiko @huningxin 

If we hard code `MinDepth` and `MaxDepth` (effective range values) in the implementation, I would expect the same camera to have the same values between browsers. Otherwise, my website could be falsely calibrated for other browsers, if I did not feature detect and handle other unexpected ranges.

This suggests such a standardization of "effective range" per camera with`MinDepth` and `MaxDepth` values to deal with conversion to 8-bit depth. This approach seems dangerous as the "effective range" values are an approximation of usable range based on use-case [1].

Alternatively, computing "effective range" does not make such use-case assumptions but does so with a considerable performance hit and still has usable 8-bit depth. It looks like the native SDKs don't really bother with 8-bit depth, so the range inverse conversion isn't required.

[1] https://software.intel.com/en-us/articles/a-comparison-of-intel-realsensetm-front-facing-camera-sr300-and-f200

**Comment by anssiko** [comment]
Ping @ds-hwang for further feedback.

**Comment by ds-hwang** [comment]
Where "rules to convert using range inverse " come from? The formula itself should be wrong.
`dn = far * (d - near) / (d * (far - near))`

In the formula, if near == 0, dn is always 1.
`dn = far * (d - near) / (d * (far - near)) = far * d / d * far = 1`

**Comment by ds-hwang** [comment]
In addition, realsense produces 16bit integer for depth. There is [two mode](https://github.com/IntelRealSense/librealsense/blob/master/doc/projection.md)
1) linear
`float depth_in_meters = scale * d16`
2) inverse
`float depth_in_meters = scale / d16`

**Comment by bbernhar** [comment]
> Where "rules to convert using range inverse " come from? The formula itself should be wrong.
> dn = far \* (d - near) / (d \* (far - near))

@ds-hwang The conversion to 8-bit depth (via _RangeInverse_) originated from the XDM format [1], AFAIK. The spec uses those rules per 6.6, but as brought up earlier, must have a positive `MinDepth` (or "effective range") for it to be meaningful.

> the depth map will only quanitize to dn=1 when near=0 

Since _mediacapture-depth_ is built on-top of _mediacapture-main_, it requires a color image bitmap type (32-bit per pixel & 8-bits per channel) for us to map (and render) depth. As @anssiko pointed out, this is largely for interop and to some extent - basic depth processing functionality.

[1] https://software.intel.com/sites/default/files/managed/b0/bf/ExtensibleDeviceMetadataXDM.pdf

**Comment by ds-hwang** [comment]
ah.. thx for pointing out.

The spec value causes additional cost for realsense...
realsense doesn't produce this exact value so have to do conversion. However, final format WebGL will use is float32 in meter, so the spec format requires redundant conversion, which is not used for application itself.

As this format cannot satisfy all devices, float32 in meter is better because all raw value from devices must be converted to float32 in meter anyway.

**Comment by bbernhar** [comment]
I believe the conversion is only necessary for `CanvasRenderingContext2D` and not a `WebGLRenderingContext`. For WebGL, it would be packed into `RGB` format in millimeters (the SI unit for depth). It does waste more B/W not having a 16-bit `DEPTH` format. But the depth value conversion to say, meters (float), is still comparatively cheap in a shader.

**Comment by huningxin** [comment]
Thanks for the discussions so far!

I understand the problem is:
1. the "effective range" is for each frame. There is no room to attach "effective range" to ImageData of canvas 2D in today's depth map redirection pipeline.
2. current "near" and "far" in spec are for "camera range". But RSSDK reports 0 for `MinDepth` of `PROPERTY_DEPTH_SENSOR_RANGE` property.

Correct?

Then, my proposal would be requiring the `near` must be positive, so in implementation:

```
near = MinDepth > 0 ? MinDepth : DepthUnitValue;
```

WDYT?

**Comment by bbernhar** [comment]
I don't think "effective range" _must_ be for each frame, as usable range values could be static but use-case specific. The spec (I believe) refers to camera range values, as the "effective range" isn't reportable by the RSSDK but otherwise documented. Since "camera range" values can report 0 for `MinDepth`, the conversion is always `dn=1` when `near = MinDepth` (see @ds-hwang proof) or if `near = DepthUnitValue`, would be `dn=0`. So `near` must be positive and less than `d`, to compute useful 8-bit mapped depth values. Unfortunately, that constraint suggests that a valid `near` value needs to be computed since the SDK could not provide it.

**Comment by huningxin** [comment]
> if near = DepthUnitValue, would be dn=0. So near must be positive and less than d,

In this case (if `near = DepthUnitValue` and `d = DepthUnitValue`), the result `dn=0` looks reasonable to me.

> I don't think "effective range" must be for each frame, as usable range values could be static but use-case specific.

I got your "effective range" idea by reading your https://github.com/w3c/mediacapture-depth/issues/125#issuecomment-219572814. I agree using "effective range" looks better as it saves bits for effective depth value according to 8 bits conversion. The problem is SDK doesn't report that. Probably, we can bring this to RSSDK team.

**Comment by ds-hwang** [comment]
"A video stream track and a depth stream track can be combined into one depth+video stream. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources."

The depth value is the value after blackbox calibration done. At this stage, encoded integer value requires very redundant conversion. Float value in meter is natural at this stage. 

In addition, browser implementation should process conversion, rather than WebGL shader. It's because it's natural to do calibration and conversion together. Each browser may implement it using OpenGL shader or some GPU API.

So I propose the depth value in the spec is just float in meter, as the spec delegates calibration to implementation.

**Comment by anssiko** [comment]
@bbernhar Yes, range linear format is from XDM. I added the missing XDM reference and CC BY attribution in 077c8dcaed294e0e33b548417f8e2b6fcb83f75e.

**Comment by bbernhar** [comment]
@huningxin 

> In this case (if near = DepthUnitValue and d = DepthUnitValue), the result dn=0 looks reasonable to me.

If I understand you correctly - it would produce `d8bit=0` (per 6.6), which doesn't look particularly useful since as `DepthUnitValue` had a valid positive value but would always be mapped to 0. In other words, if there was no conversion (`d16bit = DepthUnitValue`) you get expected results.

> I got your "effective range" idea by reading your #125 (comment). I agree using "effective range" looks better as it saves bits for effective depth value according to 8 bits conversion. The problem is SDK doesn't report that. Probably, we can bring this to RSSDK team.

Right, it seems our 8-bit conversion formula really wants "effective range" values but the SDK wouldn't report it as `MinDepth` since it's too highly use-case specific and likely better left to the application to decide.

@ds-hwang 

The depth value in the spec cannot be 32-bits due to the `<video>` sink (per earlier comments). The raw depth `units` are usually reported already in raw millimeters, so it doesn't seem less "natural". Calibration does not change the reported units.

**Comment by ds-hwang** [comment]
@bbernhar ok. understood `dn` must be integer.

@anssiko, @huningxin 8bit depth value is too low precision. Is it impossible to use 16bit depth value? When drawing it via `<video>`, RG channel will be used.

On the other hands, let me explain why calibration and depth value is related.
If you uses realsense R200, you will get different resolution color and depth frame. Even if you get same resolution of color and depth frame, each pixel doesn't map 1to1. It's called calibration we map color and depth value to 3d point space. As the spec said `The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated.`, we have to map color and depth to 3d space and then project them to 2d space. It's because
1. spec doesn't define Distortion model. so pixel space must be euclidean coordinates (i.e. 2D linear orthogonal coordinates)
2. ensure each pixel is mapped 1to1 in the pixel space.

Note: realsense R200 produce color value distorted by Brown-Conrady Distortion and depth value distorted by Inverse Brown-Conrady Distortion. It means implementation must map both color and depth pixel to euclidean coordinates. It means it requires pixel interpolation (should be bilinear interpolation).

Depth capture API get depth value from  R200 via following path, 
1. realsense gives depth values in 16bit integer. `d_16`
2. get the float in meter by `float d = realsense_depth_scale / d_16`
3. map the `float d` to euclidean coordinates pixel space, because current pixel space is distorted. (i.e. calibration)
4. get new `float d` in the euclidean coordinates by bilinear interpolation. 
5. convert `float d` to `d8bit`. lost lots of precision :(

```
float d = float_d / far;
float dn = far * (d - near) / (d * (far - near)); // convert due to video format
uint8 d8bit = dn * 255; // it's bummer.
```

6  WebGL uses `d8bit` :(

```
in shader
float depth = far * near / ( far - dn * ( far - near)); // reverse convert (feel redundant.. )
```

Note: path between 2. and 5. will be computed by GPU. VideoFrame is also backed by texture.

**If depth value is 16bit integer, precision lost is minimized** because original value is also 16bit integer.

**Comment by huningxin** [comment]
@bbernhar 

> If I understand you correctly - it would produce d8bit=0 (per 6.6), which doesn't look particularly useful since as DepthUnitValue had a valid positive value but would always be mapped to 0. In other words, if there was no conversion (d16bit = DepthUnitValue) you get expected results.

Let's say if `MinDepth` is 0, and `DepthUnitValue` is 1 mm. According to my proposal:

```
near = MinDepth > 0 ? MinDepth : DepthUnitValue;
```

It sets `near` to 1 mm.

Let's say `far` is 1200 mm. So:

If `d` is 1 mm. The `dn` would 0. It would be recovered to `near`, so `d` is recovered to 1 mm.

If `d` is 50 mm. Then the `dn` would 250. It would be recovered to 48.96 mm.

**Comment by bbernhar** [comment]
@huningxin In your second example (where `d=50`), it should be `d8bit=250` and `dn=0.98` (e.g. [0..1] range). Otherwise, the proposal LGTM. We might also add that `near` < `d` < `far` for conversion. @anssiko, WDYT?

**Comment by huningxin** [comment]
> @huningxin In your second example (where d=50), it should be d8bit=250 and dn=0.98 (e.g. [0..1] range).

Exactly. Thanks for the correction. @bbernhar

**Comment by huningxin** [comment]
@ds-hwang 

I think we don't limit the depth value of a depth stream to 8-bit integer. The 8-bit is only used when `<video>` as a sink. 

As @anssiko mentioned, when working with mediacapture-worker, the 16-bit integer would be used. 

For WebGL 1.0 texture as the sink, today's spec of [WebGLRenderingContext](http://w3c.github.io/mediacapture-depth/#webglrenderingcontext-interface) is to use `R` and `G` components to represent 16-bits. 

For WeGL 2.0, as [Kenneth Russel's suggestion](https://www.khronos.org/webgl/public-mailing-list/archives/1411/msg00024.php), for [WebGL 2.0](https://www.khronos.org/registry/webgl/specs/latest/2.0/), the `RED` format, e.g `R32F` would be appropriate. @anssiko , as WebGL 2.0 is out, we might need to update our WebGL texture sink part.

**Comment by bbernhar** [comment]
Thanks for the comments, esp. @huningxin. 

Summary of the proposed edits to the WD and close the issue:
1. Clarify `near` and `far` are camera range values (as reported by the device).
2. Note that implementations should recover `d` with `near = MinDepth > 0 ? MinDepth : DepthUnitValue`, since `near=MinDepth=0` wouldn't allow recovery.

I would opt to create (or re-open) separate and specific per sink issues for non-`8 bit` depth support.

**Comment by ds-hwang** [comment]
@huningxin Thanks for explaining.
Our spec doesn't define internal data format. It mislead `d_8bit` is internal data format.
To be clear, I would like the spec to define the depth format as **16bit unsigned integer**.

```
d_16bit = [dn * 65535]
```

And then explain how `<video>` draws depth frame in "6.6 The video element".
My proposal is "`<video>` draws the depth frame at the red channel after conversion `d_8bit = d_16bit / 255`".

On the other hands, I want to support only **WebGL2**, because
- WebGL 1 doesn't support 16bit integer texture format.
- WebGL 1 doesn't force to support vertex texture fetch, which is very important to construct vertex with depth and color.
  - `gl_MaxVertexTextureImageUnits` minimum default is 0 in WebGL and 16 in WebGL2
- WebGL 2 supports transform feedback, which is required to construct sophisticated mesh using depth frame.
- Creation of depth and color VideoFrame requires multiple render targets support, which OpenGL ES 3.0 support.
  - It's because the spec requires `The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated.`. CPU implementation is too expensive.

As WebGL 2 is released earlier than depth stream, we can depend on WebGL2. It makes our life much easier. WDYT?

In addition, Realsense R200 doesn't have near and far value. Implementation has to do hard coding of near and far value :(

**Comment by ds-hwang** [comment]
[imagebitmap extension](http://kakukogou.github.io/spec-imagebitmap-extension/#idl-def-ImageFormat.xDEPTH) defines `DEPTH` as 16-bit unsigned integer. I like 16-bit unsigned integer.

Edit by @anssiko: the canonical ImageBitmap extensions spec is at:
https://w3c.github.io/mediacapture-worker/#imagebitmap-extensions

**Comment by bbernhar** [comment]
I believe higher precision sinks are not in scope for `v1`. Also, rear-facing cameras are not required for UC1 and could be left for `v2` once we have more feedback.

> Our spec doesn't define internal data format. It mislead d_8bit is internal data format.
> To be clear, I would like the spec to define the depth format as 16bit unsigned integer.
> 
> d_16bit = [dn \* 65535]
> And then explain how <video> draws depth frame in "6.6 The video element".
> My proposal is "<video> draws the depth frame at the red channel after conversion d_8bit = d_16bit / 255".

LGTM.

**Comment by huningxin** [comment]
> As WebGL 2 is released earlier than depth stream, we can depend on WebGL2. It makes our life much easier. WDYT?

LGTM.

**Comment by ds-hwang** [comment]
@bbernhar @huningxin Thank you for positive feedback.
I submit PR #130 to apply my proposal. Could you review?

**Comment by bbernhar** [comment]
I would suggest we split PR #130 into 1) clarify depth conversion of expected ranges (from https://github.com/w3c/mediacapture-depth/pull/130/commits/96d2e99f34c574d3f9420b5ce27fb00b9dd06ddd  and my https://github.com/w3c/mediacapture-depth/issues/125#issuecomment-221078547) and 2) support for WebGL2 (per https://github.com/w3c/mediacapture-depth/pull/130/commits/d1beddad02d089c98258d36319858962b951b8cc). Issue https://github.com/w3c/mediacapture-depth/issues/125 is for the video sink requiring 8-bit depth encoding and not addressing more advanced (higher precision) sinks.

**Comment by anssiko** [comment]
@ds-hwang Could you split your PR #130 into two new PRs we can review and land separately?

**Comment by ds-hwang** [comment]
@bbernhar you asked about canvas rendering context.
After rethinking, I think depth stream should support all feature `<video>` can support. Those include canvas rendering context and webgl1 rendering context.

**Comment by anssiko** [comment]
(We switched to range linear, so the original issue https://github.com/w3c/mediacapture-depth/issues/125#issue-154108996 became a non-issue.)
