### ISSUE TITLE
Focal length seems under defined

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-depth#135]
I don't understand how to use focal length without understanding the size of the sensor in mm. If the focal length was 50 mm, what would that mean ? what would an application use it for ?

**Comment by robman** [comment]
If you combine focal length (ideally in pixels) with fov (width/height) then you can calculate image size.

**Comment by fluffy** [comment]
That seems pretty convoluted - whats the use case for this. (I'll note the draft currently says the focal length is in mm)

**Comment by robman** [comment]
Erm sorry but not sure why that's convoluted @fluffy - that's the standard math for reprojection using the [pinhole camera model](https://en.wikipedia.org/wiki/Pinhole_camera_model). But if you just want basic image size then that's already available as `width` and `height` as defined in `mediacapture-main`.

The use case for all camera intrinsics (e.g. `focal_length`) is general reprojection and includes both from planar RGBA images or validating depth.

`focal_length` is workable in `mm` but it's more convenient in `pixels` so it's using the same scale as the pixel position on the projected plane. Definitely not a blocker though.

**Comment by fluffy** [comment]
If it was in pixels, I could understand how the repojection works, but the spec clearly says it is mm which does not seem useful unless you can also get the size of the sensor in mm. As you point out in the link you provided, the formula is -y1 / f = x1/x3.  If I have y1 in pixels, and f in mm, how does this work to get the x1/x3 ratio ?

**Comment by anssiko** [comment]
Do we have a good proposal how to address this issue @robman @huningxin?

**Comment by fluffy** [comment]
Sorry I am being dense on this but I think what would help me is what is the use case where someone wants to use this? From that I think I could propose how to fix it.

**Comment by anssiko** [comment]
"What is the use case?" is a perfect question to ask in context of web specifications :-)

Given @huningxin and @robman were actively discussing this topic at the Web & VR workshop a week ago, I think they can explain the use case. As usual, without a strong use case, we should drop the feature.

**Comment by huningxin** [comment]
The use case would be reprojecting the pixel in depth map to 3D point in world coordination (point cloud). It is required by 3D reconstruction and spatial mapping applications. 

The typical reprojection algorithm based on camera intrinsics is probably as:

```
// Reproject from pixel {x, y, depth} to point {x, y, z} based on intrinsics
var x = (pixel.x - intrinsics.principalPoint.x) / intrinsics.focalLength.x;
var y = (pixel.y - intrinsics.principalPoint.y) / intrinsics.focalLength.y;

// Handle distortion based on intrinsics.coefficients if needed.

point.x = pixel.depth * x;
point.y = pixel.depth * y;
point.z = pixel.depth;
```

This algorithm requires camera intrinsics including focal length, principal point and distortion coefficients if needed. 

If the imager is not square, both x and y axis of `focalLength` need to be known. And if the principle point is not the imager center, then both x and y axis of `princialPoint` need to be provided. Even more, if considering the distortion, then the distortion `coefficients` should be known. 

And IMO, the focal length is commonly in `pixel`.

**Comment by astojilj** [comment]
Currently, we define [this](https://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary):

> partial dictionary MediaTrackSettings {
>     ...
>     _double focalLength;_
>     _double horizontalFieldOfView;_
>     _double verticalFieldOfView;_
> };

Naming and semantics of the data is fairly standardized among different device vendors:
[Microsoft Kinect2](https://msdn.microsoft.com/en-us/library/microsoft.kinect.kinect.cameraintrinsics.aspx), [Android Tango](https://developers.google.com/tango/apis/c/reference/struct/tango-camera-intrinsics) and [Intel RealSense cameras](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.h#L264) 

There is redundancy, because fovX and fovY are calculated based on focalLengthX and focalLengthY - there is no need to have them both. We should also not assume that focalLengthX = focalLengthY = focalLength.

There is a good explanation and explanation how to compute fovX and fovY at [Android Tango documentation](https://developers.google.com/tango/overview/intrinsics-extrinsics):

> Horizontal FOV = 2 \* atan(0.5 \* width / Fx)

As usually the API define focal lengths, and width and height (all in pixels), we should probably do the same and remove field of views. Plan to make a PR for this.

**Comment by robman** [comment]
That's a good summary @astojilj - I think we should simplify down the API to be inline with these.

We can definitely derive fov from image width/height and focal length x/y - so we can just drop the fov's.

And then both image width/height and focal length x/y should be in common units (pixels). So we should add in focalLengthX and focalLengthY (so agree on splitting this too).
