### ISSUE TITLE
Syncronization

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-depth#138]
The draft says things in same stream don't need to be synchronized. However, I think this should be changed. If they are in the same stream, it's critical they are synchronized, if it is not possible to synchronize them then they the depth and video tracks should be in different streams. Things using machine vision on the depth and video are going to need to know if they are synchronized or not.

**Comment by huningxin** [comment]
@fluffy , thanks for your comments!

According to https://w3c.github.io/mediacapture-depth/#implementation-considerations, the spec says 

> A video stream track and a depth stream track can be combined into one depth+video stream. The rendering of the two tracks are intended to be synchronized. The resolution of the two tracks are intended to be same. And the coordination of the two tracks are intended to be calibrated. These are not hard requirements, since it might not be possible to synchronize tracks from sources.

Does it solve this issue?

**Comment by fluffy** [comment]
There no good way for the app to find out if they are synchronized or not. I would prefer that if they can't be synchronized, just get an error if the app asks for a stream with both then the app can respond to the error by asking for each in individual streams which will work. We could solve this other ways too like a constraint that indicated synchronization required. I don't really care how we solve it, I just want an app to have a way to know if they are not synchronized. I imagine a drone doing collisions avoidance using depth and vision - you would really want to know if they were not synchronized.

**Comment by robman** [comment]
+1 for constraints and errors on this

**Comment by huningxin** [comment]
Constraints sound promising. 

The native commonly provides two directions of synchronization, say color-to-depth or depth-to-color. We probably need to support both.

Trying to post a sketch about the two cases:

Case-1: the depth-to-color case.

```
navigator.mediaDevices.getUserMedia({
  video: true,
  depth: {synchronizedTo: 'video'}
});
```

Case-2: the color-synchronized-to-depth case.

```
navigator.mediaDevices.getUserMedia({
  video: {synchronizedTo: 'depth'},
  depth: true 
});
```

When succeeded, for case 1, it resolves the promise with a media stream which has both video track and depth track where depth track is synchronized, say temporally and spatially, to video track. For case 2, the video track is synchronized to depth track accordingly.

When failed, it rejects the promise with OverconstrainedError.

@fluffy @robman what do you think?

**Comment by fluffy** [comment]
well how it work with synchronizing audio and video is if you want them synchronized the apps ask for both audio and video in a single call to GUM but if the app does not care if they are synchronized, if asks for them in two separate calls to GUM. I think that could work but what you are proposing could work too. I don't care too much which way as long as there is some way to do it.

**Comment by huningxin** [comment]
OK. I am fine with leaving the color-to-depth or depth-to-color specifying to v2. 

So for v1, we would specify that

```
navigator.mediaDevices.getUserMedia({
  video: true,
  depth: true 
});
```

When succeeded, it resolves the promise with a media stream which has both video track and depth track where the video and depth track are synchronized temporally and spatially.

When failed, it rejects the promise with OverconstrainedError.

Does it sound good? @fluffy

**Comment by robman** [comment]
+1 from me for this simple version in your latest comment for v1 @huningxin and a simple OverconstrainedError if this can't be delivered.

**Comment by fluffy** [comment]
Yah, the simple version sounds good to me. I don't even understand the difference of depth sync to color vs color sync to depth.

**Comment by huningxin** [comment]
It is about spatial synchronization:

1. depth sync to color: pixel in depth image -> (depth camera intrinsics) -> 3D point of depth camera view -> (depth-to-color camera extrinsics) -> 3D point of color camera view -> (color camera intrinsics) -> pixel in color image
2. color sync to depth is the vise versa.

**Comment by huningxin** [comment]
The difference is:
1. depth sync to color: the resolution of depth image would be resized to color image, each pixel of the depth image represents the depth value of corresponding pixel (with same (x, y)) of the color image.
2. color sync to depth: the resolution of color image would be resized to depth image, each pixel of the color image represents the RGB value of corresponding pixel (with same (x, y)) of the depth image.

**Comment by astojilj** [comment]
This approach raises performance and quality concerns.
Case1: if canvas & getImageData would be used:
1. increases bandwidth and uses CPU for upscaling depth image (e.g. SR300 from 640x480 -> 1920x1080) and depending on quality of upscaling technique could also cause filtering problems.
2. low quality.
The problem is that also 2. is not possible in general case: "Although it is inconvenient that projection and deprojection cannot always be applied to an image... " [link to RealSense distortion models](https://github.com/IntelRealSense/librealsense/blob/master/doc/projection.md#distortion-models)

Case 2: WebGL:
If synced video streams would get uploaded to two textures, and the browser would do a render pass of "projecting" 640x480 to Full HD (as the proposal here states that they should be of the same resolution) depth aligned to RGB frame, we would still have an increased bandwidth needed for Full HD.

Let's consider the pointcloud use case in details. If sync is done on CPU side (in C++)it would use something [like this ](https://github.com/IntelRealSense/librealsense/blob/master/examples/c-tutorial-3-pointcloud.c#L148).

```
rs_deproject_pixel_to_point(depth_point, &depth_intrin, depth_pixel, depth_in_meters);
rs_transform_point_to_point(color_point, &depth_to_color, depth_point);
rs_project_point_to_pixel(color_pixel, &color_intrin, color_point);
```

After this, in order to render the pointcloud, we'll need to have two synced Full HD bitmaps uploaded to textures.

Let's consider the alternative implementation using GPU only with streams that are not in sync, as projection and matrix transformation fits GPU & WebGL better.
So, we would upload videos to 2 textures; FullHD RGBA8 for color and 640x480 GL_FLOAT (R32F or RGBA32F or 16-but R16UI with WebGL2) for depth, use camera streams intrinsics and extrinsics (Issue #110) in GL shader to do the projection & distortion and render the point cloud.

My suggestion is to make #110 v1 feature as it is the lowest common denominator enabling implementation for pointcloud using different cameras - Realsense, Kinect or [Tango.](https://developers.google.com/tango/apis/c/reference/struct/tango-camera-intrinsics) and enable also using manual calibration.

It is quite possible that I missed some of the use cases that would require synchronization as planned here.

**Comment by astojilj** [comment]
> @huningxin [ commented 17 days ago](https://github.com/w3c/mediacapture-depth/issues/138#issuecomment-255908425)
> ....
> So for v1, we would specify that
> navigator.mediaDevices.getUserMedia({
>   video: true,
>   depth: true 
> });
> 
> When succeeded, it resolves the promise with a media stream which has both video track and depth track where the video and depth track are synchronized temporally and spatially.

Let's go further, with example of using this:

```
.then(function(stream) {
  var video = document.querySelector('video');
  video.src = URL.createObjectURL(stream);// or  video.srcObject = stream;
```

Which video should the code above render in video tag - rgb video or depth video?
Depth video is just a type of video, not a separate media type like audio.
When we retrieve it without rgb counterpart, we still render it to canvas or upload it to webgl. Don't think we can do that with audio, so this looks a bit counter-intuitive.

**Comment by huningxin** [comment]
> This approach raises performance and quality concerns... upscaling depth image (e.g. SR300 from 640x480 -> 1920x1080)

This is not correct. As the proposal, UA should do `color-to-depth` sync, so apps get synced depth (640x480) and color (640x480) images.

> So, we would upload videos to 2 textures; FullHD RGBA8 for color and 640x480 GL_FLOAT (R32F or RGBA32F or 16-but R16UI with WebGL2) for depth, use camera streams intrinsics and extrinsics (Issue #110) in GL shader to do the projection & distortion and render the point cloud.

This use case is only about rendering the point cloud.

> It is quite possible that I missed some of the use cases that would require synchronization as planned here.

Other use cases are about processing the point cloud, like 3D reconstruction, hand/gesture tracking and collisions avoidance (as @fluffy mentioned) etc.,.

**Comment by huningxin** [comment]
> Let's go further, with example of using this:
> 
> .then(function(stream) {
>   var video = document.querySelector('video');
>   video.src = URL.createObjectURL(stream);// or  video.srcObject = stream;
> Which video should the code above render in video tag - rgb video or depth video?

As current spec, https://w3c.github.io/mediacapture-depth/#the-video-element, it should render the rgb video.

**Comment by astojilj** [comment]
> > This approach raises performance and quality concerns... upscaling depth image (e.g. SR300 from 640x480 -> 1920x1080)
> 
> This is not correct. As the proposal, UA should do color-to-depth sync, so apps get synced depth (640x480) and color (640x480) images.

Well, that part issue is covered under:

> 1. low quality.
>    The problem is that also 2. is not possible in general case: "Although it is inconvenient that projection and deprojection cannot always be applied to an image... " [link to RealSense distortion models](https://github.com/IntelRealSense/librealsense/blob/master/doc/projection.md#distortion-models)
> 
> As current spec, https://w3c.github.io/mediacapture-depth/#the-video-element, it should render the rgb video.

Point cloud video seems like a viable alternative - if we abstract depth with the same relationship to video as audio has; audio+video are rendered together, shouldn't depth+video be rendered together?

> For a video element whose assigned media provider object is a depth+video stream, the user agent must act as if all the MediaStreamTracks of kind "depth" were removed prior to when the video element is potentially playing.

Guess that users would like to get 2 textures/bitmap, one for RGB video and one for depth video.
Video stream gets rendered to one bitmap/uploaded to one texture and depth stream to another.
Video+depth in one stream that would behave like RGB video opens a question about how to get depth video - guess that new stream needs to be constructed, depth track taken (out) from video+depth stream and added to newly constructed depth stream... so why not get two separated streams instead?
Anyway, preparing the proposal to resolve this.

**Comment by huningxin** [comment]
> guess that new stream needs to be constructed, depth track taken (out) from video+depth stream and added to newly constructed depth stream

Right. Please see "Playback of depth+video stream" example of https://w3c.github.io/mediacapture-depth/#examples

> so why not get two separated streams instead?

For common rgb + depth use cases, it requires the rgb capturing and depth capturing are synchronized. Requesting both rgb and depth in one gUM call indicates UA to enforce the synchronization, otherwise UA would not care about the synchronization.

**Comment by astojilj** [comment]
The issues identified here look resolved now.
