### ISSUE TITLE
Create "changes since FPWD" for WD1

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#42]
Example: http://www.w3.org/TR/vibration/#sotd

**Comment by anssiko** [comment]
@ningxin @robman Please use the comments to document changes since FPWD release (that is, the changes between the latest and the snapshot we released in 7 Oct 2014 http://www.w3.org/TR/2014/WD-mediacapture-depth-20141007/).

I'm happy to craft the actual PR with proposed changes based on your suggestions for changelog, thus assigned to myself.

**Comment by huningxin** [comment]
@anssiko , thanks for taking this. I will put my comments here once I complete my editing.

**Comment by huningxin** [comment]
- Remove DepthImage interface
- Add depth video support into CanvasImageSource typedef
- Add depth value presentation into ImageData interface
- Add depth track support into Direct Assignment to Media Elements
- Add depth video uploading as texture support into WebGLRenderingContext interface
- Add combined video and depth tracks section
- Add a WebGL Fragment Shader based post-processing example
- Add a 2D Canvas Context based post-processing example

**Comment by robman** [comment]
- Added CameraIntrinsics extension to MediaStreamTrack's getSettings (IANA? - Also see issue #27 for background maths info)
- Split first Terminology point into 2 and included reference to Constrainable Pattern
- Minor updates to 2D Canvas Example and general text

**Comment by anssiko** [comment]
Thanks for outlining the changes. This issues is now closed via https://github.com/w3c/mediacapture-depth/pull/62
