### ISSUE TITLE
Define constraint between video and depthVideo.

### ISSUE THREAD

**Issue by ds-hwang** [w3c/mediacapture-depth#71]
Look at the example of 2D canvas.

```
  // wire the stream into a &lt;video&gt; element for playback
  var video = document.querySelector('#video');
  video.srcObject = stream;
  video.play();
  // wire the depth stream into another &lt;video&gt; element to convert kind
  // NOTE: Only the R and G bytes are set to carry 16 bits of data
  var depthVideo = document.querySelector('#depthVideo');
  // construct a new MediaStream out of the existing depth track(stream)
  var depthStream = new MediaStream(stream.getDepthTracks()[0]);
  depthVideo.srcObject = depthStream;
  depthVideo.play();

  depthVideo.onloadedmetadata = function () {
...
  };
```

After read, I have two questions,
1. Can depthVideo.onloadedmetadata() make sure if onloadedmetadata of `video` is called?
2. What's happen if user doesn't call play() method of one of two video?

My gut feels that code should be expressed more clearly that both video play synchronously.

**Comment by anssiko** [comment]
Thanks for the feedback. This is the specified behaviour without any special casing:
1. Since `#video` and `#depthVideo` are two separate media elements, their `loadedmetadata` events (fired when the user agent has just determined the duration and dimensions of the media resource and the text tracks are ready) firing do not depend on each other. Web developers are expected to check that both elements have fired their respective events separately.
2. Only the media element on which the `play()` has been invoked on (or that has its `autoplay` attribute set) will start the playback. The other media element will remain in its `waiting` state, and when `play()` is invoked will start its playback at a position that is synchronized with the other media element playback in a best effort fashion.

The expectations regarding the best effort syncronization are clarified in the [implementation considerations](https://w3c.github.io/mediacapture-depth/#implementation-considerations) section.

I'm closing this issue now, please let us know if you feel further clarifications would be needed in the spec.
