### ISSUE TITLE
Extend ImageData to support depth data

### ISSUE THREAD

**Issue by huningxin** [w3c/mediacapture-depth#73]
Reference is: https://developers.google.com/depthmap-metadata/reference

The proposal is:

```
partial interface ImageData {
    readonly attribute Uint16Array? depth_data;
};
```

Sample code sketch is:

```
var canvasContext = document.createElement("canvas").getContext("2d");
var fps = 60;

navigator.mediaDevices.getUserMedia({
  video: true,
  depth: true,
}).then(function (stream) {
  // wire the stream into a <video> element for playback
  var video = document.querySelector('#video');
  video.srcObject = stream;  // stream carries both video and depth tracks
  video.play();

  video.onloadedmetadata = function () {
    function doSomething() {
      canvasContext.drawImage(video); // propagate both pixels and dexels.
      var imageData = canvasContext.getImageData(0, 0, w, h);
      var pixels = imageData.data;
      var dexels = imageData.depth_data;

      for (var x = 0; x < w ; ++x) {
        for (var y = 0; y < h; ++y) {
          var i = x + y * w;
          var r = pixels[i*4];
          var g = pixels[i*4 + 1];
          var b = pixels[i*4 + 2];
          var depth = dexels[i];
        }
      }
      window.requestAnimationFrame(doSomething);
    }
    window.requestAnimationFrame(doSomething);
  };
}).catch(function (reason) {
  // handle gUM error here
});

```

**Comment by ds-hwang** [comment]
The example requires huge hack in canvas, because getImageData() intend to read back from framebuffer and the framebuffer don't have depth component in general.

```
      canvasContext.drawImage(video); // propagate both pixels and dexels.
      var imageData = canvasContext.getImageData(0, 0, w, h);
      var pixels = imageData.data;
      var dexels = imageData.depth_data;
```

Let me change the proposal a bit using existing [mediacapture image spec](http://w3c.github.io/mediacapture-image/index.html#repeated-grabbing-of-a-frame)

```
partial interface ImageData {
    readonly attribute int format; // RGBA or DEPTH16
};
```

The example is very similar to the example in mediacapture image spec

```
<html>
<body>
<button onclick="stopFunction()">Stop frame grab</button>
<script>
var canvas = document.getElementById('frame');
navigator.getUserMedia({video: true, depth: true}, gotMedia, failedToGetMedia);

function gotMedia(mediastream) {
   //Extract video track.  
   var videoDevice = mediastream.getVideoTracks()[0];
   var captureDevice = new ImageCapture(videoDevice);
   var frameVar;
   if (captureDevice) {
         frameVar = setInterval(captureDevice.grabFrame().then(processFrame()), 1000);
         }
     }
   var depthDevice = mediastream.getDepthTracks()[0];
   var captureDepthDevice = new ImageCapture(videoDevice);
   var depthVar;
   if (captureDepthDevice) {
         depthVar = setInterval(captureDepthDevice.grabFrame().then(processDepthFrame()), 1000);
         }
     }

 function processFrame(e) {
     imgData = e.imageData;
     canvas.width = imgData.width;
     canvas.height = imgData.height;
     ASSERT(imgData.format == RGBA);
     canvas.getContext('2d').drawImage(imgData, 0, 0,imgData.width,imgData.height);
     }

 function processDepthFrame(e) {
     imgData = e.imageData;
     ASSERT(imgData.format == DEPTH16);
     // do something
     }

 function stopFunction(e) {
     clearInterval(frameVar);
     clearInterval(depthVar);
     }
</script>
</body>
</html>   
```

**Comment by robman** [comment]
Hi Dongseong,

I really like the elegance of your "format" suggestion...but this won't 
allow us to have both pixels and dexels in one calibrated object - I 
think @ningxin mentioned this at the end of his last email.

Do you have any thoughts on how this might work?

roBman

**Comment by huningxin** [comment]
> The example requires huge hack in canvas, because getImageData() intend to read back from framebuffer and the framebuffer don't have depth component in general.

As my understanding, `imageData.depth_data` is a kind of metadata and not used for rendering. So it doesn't require framebuffer has depth component and big modifications to canvas context 2d implementation. 

IMO, it needs to extend canvas context 2d and html video to support:
1. when `drawImage` is invoked, canvas is able to draw depth video track besides rgb video track. 
   1. The drawing of rgb video track goes original path (for rendering).
   2. canvas is able to 'draw' (fetch) the frame of depth video track into a Uint16Array buffer within canvas, say depthbuffer. (not for rendering).
2. when `getImageData` is invoked, canvas is able to create ImageData with pixels (`data`) from underlying framebuffer and dexels (`depth_data`) from internal depthbuffer.

@ds-hwang , do you think whether this sketch work?

**Comment by robman** [comment]
+1 8)

On 26/02/15 2:13 PM, Ningxin Hu wrote:

> 1. when |drawImage| is invoked, canvas is able to draw depth video
>    track besides rgb video track.
>    1. The drawing of rgb video track goes original path (for rendering).
>    2. canvas is able to 'draw' (fetch) the frame of depth video
>       track into a Uint16Array buffer within canvas, say
>       depthbuffer. (not for rendering).
> 2. when |getImageData| is invoked, canvas is able to create ImageData
>    with pixels (|data|) from underlying framebuffer and dexels
>    (|depth_data|) from internal depthbuffer.

roBman

**Comment by ds-hwang** [comment]
The implementation is possible but canvas author won't like this idea.

> 1. when drawImage is invoked, canvas is able to draw depth video track besides rgb video track.
>    1. The drawing of rgb video track goes original path (for rendering).
>    2. canvas is able to 'draw' (fetch) the frame of depth video track into a Uint16Array buffer within canvas, say depthbuffer. (not for rendering).

Canvas have to keep the depth frame in temporary buffer. It's not related to any functionality of canvas. 

> 1. when getImageData is invoked, canvas is able to create ImageData with pixels (data) from underlying framebuffer and dexels (depth_data) from internal depthbuffer.

If getImageData is not invoked, how long canvas should keep the temporary buffer?

In addition, video element containing both video track and depth track is also problematic.

```
  var video = document.querySelector('#video');
  video.srcObject = stream;  // stream carries both video and depth tracks
  video.play();
```

because
1.  from implementation perspective, VideoFrame internal structure contains only one buffer, whose type can be RGB, RGBA, YUV, YV12, or Texture. It's difficult to expend VideoFrame to have depth trace. I guess Video forks won't agree. However, it's easy to expend VideoFrame to have sorta LUMINANCE16 format.
2. from visualization perspective, depth track of the video doesn't have any visual effect.

Did we make a consensus for video to include both video track and depth track?

**Comment by robman** [comment]
> 1. from implementation perspective, VideoFrame internal structure contains only one buffer, whose type can be RGB, RGBA, YUV, YV12, or Texture. It's difficult to expend VideoFrame to have depth trace. I guess Video forks won't agree. However, it's easy to expend VideoFrame to have sorta LUMINANCE16 format.

Some 16 bit format (e.g. LUMINANCE16) would be ideal. But at the moment for phase1 we're just using the standard 32 bit RGBA type and we put the depth data in the R and G channels. This is pragmatic because it works with the existing drawImage/getImageData RGBA focused model. 

By extending HTMLVideoElement.srcObject() to allow us to cast MST.kind=depth to (VideoTrack.kind=main && VideoTrack.selected=true) we can assume that after casting this VideoTrack behaves like any other VideoTrack. This is for the single depth track scenario. Then we recombine the R & G into a 16 bit value after this in either js or a fragment shader. See below for the other scenario.

> 1. from visualization perspective, depth track of the video doesn't have any visual effect.

Well if the MST.kind=depth is cast to (VideoTrack.kind=main && VideoTrack.selected=true) then it will be rendered into the Canvas' 32 bit RGBA buffer as described above. In this case it doesn't matter what the rendered pixels look like as long as the R & G channels are populated and lossless.

But if the MST.kind=depth is cast to (VideoTrack.kind=alternative || VideoTrack.selected=false) then this track will be ignored by the HTMLVideoElement and visually it doesn't matter. As long as this can be extracted into .depth_data as @ningxin proposed then we're all good (either as 16bit or half 32 bit).

@ningxin based on this discussion I can see why you'd like to make VideoTrack.kind=depth so we can identify these tracks explicitly here. From my perspective I'd rather be able to access the MST from the HTMLVideoElement...but perhaps that's a different discussion 8)

> If getImageData is not invoked, how long canvas should keep the temporary buffer?

I think it would just be kept until the next drawImage()

**Comment by ds-hwang** [comment]
> From my perspective I'd rather be able to access the MST from the HTMLVideoElement...but perhaps that's a different discussion 8)

We should decide either of 
1. HTMLVideoElement containing both video and depth track
2. HTMLVideoElement containing either video or depth track

Supporting both would make confusion. From implementation view, option 1 causes huge changes.

> > If getImageData is not invoked, how long canvas should keep the temporary buffer?
> 
> I think it would just be kept until the next drawImage()

I think Canvas spec owner disagree on this change. The API looks weird. We should get the value from HTMLVideoElement or depth track directly.

**Comment by huningxin** [comment]
Extending [mediacapture image spec](http://w3c.github.io/mediacapture-image/index.html#repeated-grabbing-of-a-frame) looks like a good alternative. Based on @ds-hwang 's idea, I put together a proposal as https://github.com/w3c/mediacapture-depth/issues/76. @robman @ds-hwang , please take a look there. Thanks!

**Comment by anssiko** [comment]
@robman said:

> From my perspective I'd rather be able to access the MST from the HTMLVideoElement...but perhaps that's a different discussion 8)

@robman With newly minted http://w3c.github.io/mediacapture-fromelement/ you can do that.

@huningxin Can we close this i.e. does https://github.com/w3c/mediacapture-depth/issues/76 cover all the relevant bits discussed here?

**Comment by anssiko** [comment]
Closed via https://github.com/w3c/mediacapture-depth/pull/77
