### ISSUE TITLE
Ensure the unit constrainable property is specified per the extensibility guidelines

### ISSUE THREAD

**Issue by robman** [w3c/mediacapture-depth#8]
Do this once the the gUM spec has reached consensus on the new constraints/capabilities model.

**Comment by anssiko** [comment]
We'll need to expand the following in Section 5.1 if/when Constraints stabilizes:

> If a Constraints structure is provided, it further specifies the nature and settings of the depth track.

**Comment by robman** [comment]
We'll deal with this in phase2.

**Comment by anssiko** [comment]
The mediacapture-main has since baked in extensibility guidelines, the guideline specific to this issue is [Defining a new constrainable property](http://w3c.github.io/mediacapture-main/#h-defining-a-new-constrainable-property):

> This will require thinking through and defining how Constraints, Capabilities, and Settings for the property (see 3. Terminology) will work. The relevant text in MediaTrackSupportedConstraints, MediaTrackCapabilities, MediaTrackConstraints, MediaTrackSettings, 4.3.9 Constrainable Properties, and MediaStreamConstraints are the model to use.

For v1, we extend [MediaTrackConstraints](https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaTrackConstraintSet) with one new constrainable property [`unit`](http://w3c.github.io/mediacapture-depth/#mediatrackconstraints-dictionary).

v1 action is to check we satisfy the guidelines for `unit`.
