### ISSUE TITLE
Are enum VideoFacingModeEnum enough for future depth camera application

### ISSUE THREAD

**Issue by ChiahungTai** [w3c/mediacapture-depth#83]
I think current VideoFacingModeEnum will not be enough in HoloLen-like case.
HoloLen has two depth camera. Left and right from their HMD. So does that make sense to have something like "environment left/right"?
@anssiko, @huningxin how do you think?

**Comment by anssiko** [comment]
If devices like HoloLens will proliferate we certainly need to extend the `VideoFacingModeEnum` to support the use cases such devices enable.

For the more mainstream devices with just a single depth camera the current `"user"` and `"environment"` should be fine for a while, I believe.

Naming the enum values is not so trivial actually. There's a good related discussion in the context of sensor APIs, see [1]. The naming problem is not specific to `VideoFacingModeEnum`, but a more generic one. We should reuse the learning from [1] when it ships.

There's one practical thing to consider spec-wise:

From the WebIDL point of view, "partial enum" does not exists, see [2]. That is, we cannot extend the `enum VideoFacingModeEnum` in the extension specs, e.g. in [3]. This means we need to patch the base spec [4]. Since [4] is undergoing a stabilization, there's a bit of reluctancy for adding new features. I expect the time will solve this issue however.

Do you think we could ship v1 of [3] with the current `VideoFacingModeEnum` and look into adding more enum values in a future release when such devices might be more widely available in the market, and we have a good idea how to do it the right way?

[1] https://github.com/w3c/sensors/issues/26
[2] https://www.w3.org/Bugs/Public/show_bug.cgi?id=27048
[3] http://w3c.github.io/mediacapture-depth/
[4] http://w3c.github.io/mediacapture-main/#idl-def-VideoFacingModeEnum

**Comment by ChiahungTai** [comment]
I think we could ship v1 of [3] with the current VideoFacingModeEnum and look into adding more enum values in a future release. Because there is no HoloLens sdk documents available now, so it's hard to predict what is the best choice.

**Comment by ds-hwang** [comment]
@ChiahungTai could you give a link about 2 depth camera of HoloLens?
[HoloLens hareware details](https://developer.microsoft.com/en-us/windows/holographic/hardware_details) says "1 depth camera".

In addition, `left` and `right` mode in `VideoFacingModeEnum` is not needed. Even if the devices has two infrared cameras, all the devices (as far as I know) gives you single depth frame after compilicated computation.
For example, Realsense R200 has two infrared cameras but output one depth frame. Of course, you can get the two raw infrared frames but it's not in the scope of spec.

**Comment by ChiahungTai** [comment]
@ds-hwang 
I am wrong. This issue is filed before the detail of HoloLens' HW released. Thanks for the correction.

**Comment by robman** [comment]
I think FacingMode is underspecified across the board 8)

But we can close this now can't we @anssiko ?

**Comment by astojilj** [comment]
This seems resolved now.
